# Generated by Django 4.2.3 on 2023-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_rename_equipment_taken_loan_time_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='all_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='equipment_returned',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='loan',
            name='equipment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='loan',
            name='time_returned',
            field=models.DateTimeField(),
        ),
    ]
