# Generated by Django 4.2.3 on 2023-09-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loan_date_alter_loan_equipment_returned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_taken', models.TimeField(auto_now_add=True)),
                ('room', models.CharField(default='0.00', max_length=10)),
                ('ref_box', models.CharField(max_length=10)),
                ('ret', models.CharField(max_length=10)),
                ('model_eye', models.CharField(max_length=10)),
                ('budgy_stick', models.BooleanField(default=False)),
                ('pd_ruler', models.BooleanField(default=False)),
                ('occluder', models.BooleanField(default=False)),
                ('recording_eq', models.CharField(max_length=10)),
                ('time_returned', models.TimeField(default='12:00')),
                ('all_returned', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.student')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_taken', models.TimeField(auto_now_add=True)),
                ('room', models.CharField(default='0.00', max_length=10)),
                ('volk', models.CharField(max_length=10)),
                ('ophthalmoscope', models.CharField(max_length=10)),
                ('ant_eye', models.CharField(max_length=10)),
                ('post_eye', models.CharField(max_length=10)),
                ('focusrod', models.CharField(max_length=10)),
                ('stand', models.BooleanField(default=False)),
                ('recording_eq', models.CharField(max_length=10)),
                ('time_returned', models.TimeField(default='12:00')),
                ('all_returned', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.student')),
            ],
        ),
    ]
