# Generated by Django 4.2.3 on 2023-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_health_recording_eq_alter_ref_recording_eq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='budgy_stick',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='occluder',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='pd_ruler',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
