# Generated by Django 4.2.3 on 2023-09-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_ref_budgy_stick_alter_ref_occluder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='stand',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
